name: Build Kernel (sukisusfs)

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          echo "ANYKERNEL_SOURCE=$(grep -w "ANYKERNEL_SOURCE" config.env | head -n1 | cut -d "=" -f2)" >> $GITHUB_ENV
          echo "ANYKERNEL_SOURCE_BRANCH=$(grep -w "ANYKERNEL_SOURCE_BRANCH" config.env | head -n1 | cut -d "=" -f2)" >> $GITHUB_ENV
          echo "KERNEL_SOURCE=$(grep -w "KERNEL_SOURCE" config.env | head -n1 | cut -d "=" -f2)" >> $GITHUB_ENV
          echo "KERNEL_SOURCE_BRANCH=$(grep -w "KERNEL_SOURCE_BRANCH" config.env | head -n1 | cut -d "=" -f2)" >> $GITHUB_ENV
          echo "KERNEL_CONFIG=$(grep -w "KERNEL_CONFIG" config.env | head -n1 | cut -d "=" -f2)" >> $GITHUB_ENV
          echo "BUILD_ARGS=$(grep -w "BUILD_ARGS" config.env | head -n1 | cut -d ":" -f2)" >> $GITHUB_ENV

          sudo apt-get update
          sudo apt-get install -y python2 libncurses5 libselinux-dev
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
          sudo update-alternatives --set python /usr/bin/python2

      - name: Pull toolchain
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64-linux-android-4.9
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9
          git clone https://github.com/xiangfeidexiaohuo/Snapdragon-LLVM.git clang

      - name: Pull kernel source
        run: |
          git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} kernel-source

      - name: Integrate SukiSU (manual hook) + optional susfs
        run: |
          set -euxo pipefail
          cd kernel-source

          # Base integration (manual hook, no kprobe)
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" \
            | bash -s susfs-nongki

          # Inject kernel hooks
          inject_block() {
            local file="$1"; local anchor="$2"; shift 2
            local tmp="$(mktemp)"
            grep -Eq "$anchor" "$file" || { echo "[FATAL] Anchor not found: $anchor in $file"; exit 1; }
            awk -v r="$anchor" -v block="$*" '
              BEGIN{p=0}
              {print; if ($0 ~ r && !p){print block; p=1}}
              END{ if(p==0) exit 2 }
            ' "$file" > "$tmp" && mv "$tmp" "$file"
          }

          # fs/exec.c
          inject_block fs/exec.c "do_execveat_common\\(" \
"#ifdef CONFIG_KSU
extern bool ksu_execveat_hook __read_mostly;
extern int ksu_handle_execveat(int*, struct filename**, void*, void*, int*);
extern int ksu_handle_execveat_sucompat(int*, struct filename**, void*, void*, int*);
#endif"
          inject_block fs/exec.c "return __do_execve_file\\(" \
"#ifdef CONFIG_KSU
  if (unlikely(ksu_execveat_hook))
    ksu_handle_execveat(&fd, &filename, &argv, &envp, &flags);
  else
    ksu_handle_execveat_sucompat(&fd, &filename, &argv, &envp, &flags);
#endif"

          # fs/open.c
          inject_block fs/open.c "long do_faccessat\\(|SYSCALL_DEFINE3\\(faccessat" \
"#ifdef CONFIG_KSU
extern int ksu_handle_faccessat(int*, const char __user **, int*, int*);
#endif"
          inject_block fs/open.c "lookup_flags = .*" \
"#ifdef CONFIG_KSU
  ksu_handle_faccessat(&dfd, &filename, &mode, NULL);
#endif"

          # fs/read_write.c
          inject_block fs/read_write.c "ssize_t vfs_read\\(" \
"#ifdef CONFIG_KSU
extern bool ksu_vfs_read_hook __read_mostly;
extern int ksu_handle_vfs_read(struct file**, char __user **, size_t*, loff_t**);
#endif"
          inject_block fs/read_write.c "ssize_t vfs_read\\([^)]*\\)\\s*\\{" \
"#ifdef CONFIG_KSU
  if (unlikely(ksu_vfs_read_hook))
    ksu_handle_vfs_read(&file, &buf, &count, &pos);
#endif"

          # fs/stat.c
          if grep -q "int vfs_statx" fs/stat.c; then
            inject_block fs/stat.c "int vfs_statx\\(" \
"#ifdef CONFIG_KSU
extern int ksu_handle_stat(int*, const char __user **, int*);
#endif"
            inject_block fs/stat.c "int vfs_statx\\([^)]*\\)\\s*\\{" \
"#ifdef CONFIG_KSU
  ksu_handle_stat(&dfd, &filename, &flags);
#endif"
          else
            inject_block fs/stat.c "int vfs_fstatat\\(" \
"#ifdef CONFIG_KSU
extern int ksu_handle_stat(int*, const char __user **, int*);
#endif"
            inject_block fs/stat.c "int vfs_fstatat\\([^)]*\\)\\s*\\{" \
"#ifdef CONFIG_KSU
  ksu_handle_stat(&dfd, &filename, &flag);
#endif"
          fi

          cd ..

      - name: Build kernel
        run: |
          set -euxo pipefail
          export KBUILD_BUILD_USER="hiahia"
          export PATH=$GITHUB_WORKSPACE/clang/bin:${PATH}

          args="                  ARCH=arm64 \
                                  O=../out \
                                  ${{ env.BUILD_ARGS }} \
                                  CLANG_TRIPLE=aarch64-linux-gnu- \
                                  CROSS_COMPILE=$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin/aarch64-linux-android- \
                                  CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin/arm-linux-androideabi- "

          cd kernel-source

          make ARCH=arm64 ${KERNEL_CONFIG}

          ./scripts/config --file arch/arm64/configs/${KERNEL_CONFIG} \
            --enable CONFIG_KSU \
            --enable CONFIG_KSU_MANUAL_HOOK \
            --disable CONFIG_KPROBES \
            --disable CONFIG_KPROBE_EVENTS \
            --enable CONFIG_ZRAM \
            --enable CONFIG_ZRAM_WRITEBACK \
            --enable CONFIG_CRYPTO_ZSTD \
            --enable CONFIG_ZSTD_COMPRESS \
            --enable CONFIG_ZSTD_DECOMPRESS \
            --set-str CONFIG_ZRAM_DEFAULT_COMP "zstd" \
            --enable CONFIG_ZRAM_DEF_COMP_ZSTD \
            --enable CONFIG_ZRAM_MEMORY_TRACKING \
            --enable CONFIG_KPM \
            --enable CONFIG_KALLSYMS \
            --enable CONFIG_KALLSYMS_ALL \
            --disable CONFIG_DEFAULT_CFQ \
            --set-str CONFIG_DEFAULT_IOSCHED "kyber" \
            --enable CONFIG_MQ_IOSCHED_KYBER \
            --enable CONFIG_IOSCHED_CFQ \
            --enable CONFIG_CFQ_GROUP_IOSCHED

          grep -E 'CONFIG_KSU|CONFIG_KPM|CONFIG_KALLSYMS|CONFIG_KPROBES' arch/arm64/configs/${KERNEL_CONFIG}

          make ${args} ${KERNEL_CONFIG}

          for sym in ksu_handle_execveat ksu_handle_execveat_sucompat ksu_handle_faccessat ksu_handle_vfs_read ksu_handle_stat; do
            grep -R "$sym" . || { echo "[FATAL] Missing symbol: $sym"; exit 1; }
          done

          clang -v
          make -j$(nproc --all) ${args}

      - name: Package kernel
        run: |
          git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_SOURCE_BRANCH
